version: "3.8"

services:
  dev:
    build:
      context:
      dockerfile: Dockerfile.dev
    container_name: slieth-dev
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - .:/slieth
      - /slieth/node_modules
      - /slieth/.next
    ports:
      - "1234:1234"
    env_file:
      - .env.local
  prod:
      build:
        context:
        dockerfile: Dockerfile.prod
      container_name: slieth-prod
      volumes:
      - .:/slieth
      - /slieth/node_modules
      - /slieth/.next
      ports:
      - "1234:1234"
      env_file:
      - .env.local
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

