services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/src"
  mongodb:
      container_name: slieth_db
      image: mongo:latest
      volumes:
        - ./scripts/mongo/init/:/docker-entrypoint-initdb.d
        - ./scripts/mongo/init:/home/mongodb
        - slieth_data:/data/db
      ports:
        - "28017:27017"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
        - APP_USER=$APP_USER
        - APP_PWD=$APP_PWD
        - DB_NAME=$DB_NAME
        - DB_COLLECTION_NAME=$DB_COLLECTION_NAME
        - MONGO_HOSTNAME=$MONGO_HOSTNAME
volumes: 
  slieth_data:

