FROM node:22 AS base
WORKDIR /slieth
RUN npm i -g pnpm
COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .
RUN pnpm build

FROM node:22-alpine3.22 as release
WORKDIR /slieth
RUN npm i -g pnpm

COPY --from=base /slieth/node_modules ./node_modules
COPY --from=base /slieth/package.json ./package.json
COPY --from=base /slieth/.next ./.next

EXPOSE 1234

CMD ["pnpm", "dev"]
